env:
  browser: true
  es2021: true
  node: true
extends:
  - next
  - prettier
  - standard-with-typescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - simple-import-sort
  - unused-imports
rules:
  "@typescript-eslint/comma-dangle": ["warn", "always-multiline"]
  "space-before-function-paren": "off"
  "@typescript-eslint/space-before-function-paren": ["off", "never"]
  "@typescript-eslint/explicit-function-return-type": "off"
  "@typescript-eslint/consistent-type-definitions": ["error", "type"]
  "@typescript-eslint/strict-boolean-expressions": "off"
  "@typescript-eslint/no-misused-promises":
    ["error", { checksVoidReturn: false }]
  "@typescript-eslint/indent": "off"
  "@typescript-eslint/member-delimiter-style": "off"
  "@typescript-eslint/no-dynamic-delete": "off"
  "@typescript-eslint/no-confusing-void-expression": "off"
  "multiline-ternary": "off"
  "unused-imports/no-unused-imports": "error"
  "unused-imports/no-unused-vars":
    [
      "warn",
      {
        "vars": "all",
        "varsIgnorePattern": "^_",
        "args": "after-used",
        "argsIgnorePattern": "^_",
      },
    ]
  "react/no-unescaped-entities": "off"
ignorePatterns:
  - "lib/database.types.ts"
  - "*.js"
  - "*.jsx"
overrides:
  - files: ["*.js", "*.jsx", "*.ts", "*.tsx"]
    rules:
      "simple-import-sort/imports":
        [
          "error",
          {
            groups:
              [
                ["^react", "^@?\\w"],
                ["^(@|components)(/.*|$)"],
                ["^\\u0000"],
                ["^\\.\\.(?!/?$)", "^\\.\\./?$"],
                ["^\\./(?=.*/)(?!/?$)", "^\\.(?!/?$)", "^\\./?$"],
                ["^.+\\.?(css)$"],
              ],
          },
        ]
